import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { CLI_EXIT_CODES, runCli, type CliRuntime } from "@dvw/cli";
import {
  createReviewFeedbackPacket,
  feedbackContextFromReview,
  serializeReviewFeedbackPacket,
} from "@dvw/feedback";
import type { ReviewArtifactInput } from "@dvw/review-artifact";
import { buildReviewFixture } from "./fixture.js";

function writeCreateOnly(path: string, value: string): void {
  try {
    writeFileSync(path, value, { encoding: "utf8", flag: "wx", mode: 0o600 });
  } catch (error) {
    if (
      !(error instanceof Error) ||
      !("code" in error) ||
      error.code !== "EEXIST" ||
      readFileSync(path, "utf8") !== value
    ) {
      throw error;
    }
  }
}

function embeddedInput(path: string): ReviewArtifactInput {
  const html = readFileSync(path, "utf8");
  const raw = html.match(
    /<script type="application\/json" id="review-data">([\s\S]*?)<\/script>/u,
  )?.[1];
  if (raw === undefined)
    throw new Error("Regenerated HTML has no review data.");
  return (JSON.parse(raw) as { review: ReviewArtifactInput }).review;
}

function runtime(root: string): CliRuntime {
  return {
    artifactsRoot: join(root, "unused-cli-artifacts"),
    databasePath: join(root, "unused.sqlite"),
    defaultProviderId: "unavailable",
    generationId: () => {
      throw new Error("Feedback fixture cannot create a scan generation.");
    },
    now: () => "2026-08-08T16:01:00.000Z",
    planning: {
      build: () => {
        throw new Error("Feedback fixture cannot call the planning runtime.");
      },
    },
    policyVersion: "1.0.0",
    providers: {
      select: () => {
        throw new Error("Feedback fixture cannot select a Drive provider.");
      },
    },
  };
}

const workspaceRoot = resolve(process.cwd());
const outputRoot = join(workspaceRoot, "artifacts/local/feedback-roundtrip");
const built = buildReviewFixture({
  artifactRoot: join(outputRoot, "source-html"),
  labRoot: join(outputRoot, "lab"),
});
const action = built.input.plan.actions[0];
const question = built.input.questions[0];
if (action === undefined || question === undefined) {
  throw new Error("Feedback round-trip fixture is incomplete.");
}
const packet = createReviewFeedbackPacket(
  feedbackContextFromReview(built.input),
  {
    actions: [
      {
        actionId: action.actionId,
        comment: "Browser fixture action comment.",
        disposition: "Edit",
        proposedName: "2026-08-02 - Hotel Paisano - Paid Invoice.pdf",
        reason: {
          code: "PAID_DATE_CONFIRMED",
          detail: "Browser fixture structured reason.",
        },
      },
    ],
    globalComment: "Browser fixture global comment; feedback only.",
    questions: [
      {
        answer: question.choices[0]!,
        comment: "Browser fixture question comment.",
        questionKey: question.questionKey,
        scope: question.scope,
      },
    ],
  },
  {
    exportedAt: "2026-08-08T16:00:00.000Z",
    reviewer: "Buck reviewer",
  },
);
const packetText = serializeReviewFeedbackPacket(packet);
const canonicalFixturePath = join(
  workspaceRoot,
  "tests/integration/feedback/fixtures/review-feedback-v1.json",
);
if (readFileSync(canonicalFixturePath, "utf8") !== packetText) {
  throw new Error("Canonical feedback fixture does not match generated bytes.");
}
const inputPath = join(
  outputRoot,
  `review-input-${built.input.plan.planHash}.json`,
);
writeCreateOnly(inputPath, `${JSON.stringify(built.input, null, 2)}\n`);
const cliRuntime = runtime(outputRoot);
const reviewResult = await runCli(
  [
    "review",
    "--input",
    inputPath,
    "--output-dir",
    join(outputRoot, "cli-html"),
  ],
  cliRuntime,
);
const feedbackResult = await runCli(
  [
    "feedback",
    "import",
    "--input",
    inputPath,
    "--output-dir",
    join(outputRoot, "cli-html"),
    "--packet-json",
    packetText,
  ],
  cliRuntime,
);
if (
  reviewResult.exitCode !== CLI_EXIT_CODES.SUCCESS ||
  feedbackResult.exitCode !== CLI_EXIT_CODES.SUCCESS ||
  feedbackResult.output.command !== "feedback"
) {
  throw new Error("HTML-to-CLI-to-HTML fixture command failed.");
}
const regenerated = embeddedInput(feedbackResult.output.data.artifactPath);
const reexported = regenerated.importedFeedback;
if (
  reexported === undefined ||
  serializeReviewFeedbackPacket(reexported) !== packetText
) {
  throw new Error("Regenerated HTML did not preserve canonical packet bytes.");
}
const transcript = {
  approvalGranted: feedbackResult.output.data.approvalGranted,
  canonicalPacketPath: canonicalFixturePath,
  changedPlanHash:
    feedbackResult.output.data.nextPlanHash !==
    feedbackResult.output.data.sourcePlanHash,
  commands: [
    `dvw review --input ${inputPath} --output-dir ${join(outputRoot, "cli-html")}`,
    "dvw feedback import --packet-json <canonical packet> --input <same review> --output-dir <same artifact root>",
  ],
  feedback: feedbackResult.output,
  feedbackText: feedbackResult.text,
  packetBytesStable: true,
  review: reviewResult.output,
  reviewText: reviewResult.text,
  sourceArtifactPath: built.artifactPath,
  sourceInputUnchanged:
    readFileSync(inputPath, "utf8") ===
    `${JSON.stringify(built.input, null, 2)}\n`,
  zeroProviderSelections: true,
};
const transcriptText = `${JSON.stringify(transcript, null, 2)}\n`;
const transcriptHash = createHash("sha256")
  .update(transcriptText)
  .digest("hex");
const transcriptPath = join(
  outputRoot,
  `transcript-${packet.checksum}-${transcriptHash}.json`,
);
writeCreateOnly(transcriptPath, transcriptText);
process.stdout.write(
  `${JSON.stringify(
    {
      artifactPath: feedbackResult.output.data.artifactPath,
      importedChecksum: packet.checksum,
      nextPlanHash: feedbackResult.output.data.nextPlanHash,
      packetBytesStable: true,
      sourcePlanHash: feedbackResult.output.data.sourcePlanHash,
      transcriptPath,
    },
    null,
    2,
  )}\n`,
);
